[package]
name = "dubs_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.12.0"
is_prime = "2.0.9"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }