services:
  database:
    image: postgres:latest
    container_name: dubs-bot-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dubs
      POSTGRES_USER: dubs
      POSTGRES_PASSWORD: dubs

  prometheus:
    image: prom/prometheus
    container_name: dubs-bot-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - "./docker/prometheus.yml:/etc/prometheus/prometheus.yml"
