services:
  database:
    image: postgres:latest
    container_name: dubs-bot-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dubs
      POSTGRES_USER: dubs
      POSTGRES_PASSWORD: dubs
