spring:
  datasource:
    url: ${DATBASE_URL:jdbc:postgresql://localhost:5432/dubs}
    username: ${DATABASE_USERNAME:dubs}
    password: ${DATABASE_PASSWORD:dubs}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

discord:
  token: ${DISCORD_TOKEN}
  development-guild-id: 932728712355512331
