spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/dubs}
    username: ${DATABASE_USERNAME:dubs}
    password: ${DATABASE_PASSWORD:dubs}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:/changelog.sql

logging:
  level:
    org.springframework.jdbc.core: DEBUG

discord:
  token: ${DISCORD_TOKEN}
  development-guild-id: ${DISCORD_DEVELOPMENT_GUILD_ID:932728712355512331}