--liquibase formatted sql

--changeset jirkavrba:create-guild-settings-table
create table guild_settings
(
    id               int         not null generated by default as identity primary key,
    guild_id         bigint      not null unique,
    dubs_lookup_mode varchar(32) not null
);

create index ix_guild_settings_guild_id on guild_settings (guild_id);