--liquibase formatted sql

--changeset jirkavrba:create-guild-settings-table
create table guild_settings
(
    id               int         not null generated by default as identity primary key,
    guild_id         bigint      not null unique,
    dubs_lookup_mode varchar(32) not null
);

create index ix_guild_settings_guild_id on guild_settings (guild_id);

--changeset jirkavrba:create-guild-stats-table
create table guild_stats
(
    id                  int    not null generated by default as identity primary key,
    guild_id            bigint not null unique,
    messages_count      bigint not null,
    digits_count        bigint not null,
    extra_matches_count bigint not null
);

create index ex_guild_stats_guild_id on guild_stats (guild_id);

--changeset jirkavrba:create-user-scores-table
create table user_scores
(
    id                int    not null generated by default as identity primary key,
    user_id           bigint not null,
    guild_id          bigint not null,
    score_date        date   not null,
    digits_score      int[]  not null,
    cons_score        int    not null,
    off_by_ones_score int    not null,
    palindromes_score int    not null,
    primes_score      int    not null
);

alter table user_scores add constraint uk_user_scores_user_guild_date unique (user_id, guild_id, score_date);

create index ix_user_scores on user_scores (user_id, guild_id, score_date);