micronaut:
  application:
    name: dubs-bot-api

  server:
    port: ${PORT:8080}

  serde:
    serialization:
      inclusion: always

  metrics:
    enabled: true
    binders:
      jdbc.enabled: false
      jvm.enabled: false
      logback.enabled: false
      processor.enabled: false
      files.enabled: false
      uptime.enabled: false
      web.enabled: false
      executor.enabled: false
    export:
      prometheus:
        enabled: true
        descriptions: false
        step: PT60S

  endpoints:
    prometheus:
      enabled: true
      sensitive: false

datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
    url: jdbc:postgresql://${DATABASE_URL:`localhost:5432/dubs`}
    username: ${DATABASE_USERNAME:dubs}
    password: ${DATABASE_PASSWORD:dubs}

flyway:
  datasources:
    default:
      enabled: true

jpa:
  default:
    entity-scan:
      packages: dev.vrba.dubs.domain
    properties:
      hibernate:
        hbm2ddl:
          auto: none
