micronaut:
  application:
    name: dubs-bot-api
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
flyway:
  datasources:
    default:
      enabled: true
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
