micronaut:
  application:
    name: dubs-bot-api

  serde:
    serialization:
      inclusion: always

  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M

  security:
    basic-auth:
      enabled: true
    intercept-url-map:
      - pattern: "/api/v1/bot/**"
        access:
          - ROLE_BOT

      - pattern: "/prometheus"
        http-method: "GET"
        access:
          - "isAnonymous()"

  endpoints:
    prometheus:
      enabled: true
      sensitive: false

credentials:
  bot-user:
    username: ${BOT_USER_USERNAME:bot}
    password: ${BOT_USER_PASSWORD:bot}

datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
    url: jdbc:postgresql://${DATABASE_URL:`localhost:5432/dubs`}
    username: ${DATABASE_USERNAME:dubs}
    password: ${DATABASE_PASSWORD:dubs}

flyway:
  datasources:
    default:
      enabled: true
      locations:
        - classpath:migrations

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
