scrape_configs:
  - job_name: prometheus
    honor_labels: true
    static_configs:
      - targets:
        - "host.docker.internal:8080"
    scrape_interval: 30s
    scrape_timeout: 5s
    body_size_limit: 10MB
    sample_limit: 1000
    target_limit: 35
    label_limit: 35
    label_name_length_limit: 210
    label_value_length_limit: 210
    metrics_path: /prometheus
    scheme: http
